### ISSUE TITLE
|BUG| Overriding Note size with Small Notes modifier changes note hitbox to be BIGGER while still submitting to BeatLeader, ScoreSaber.

### ISSUE THREAD

**Issue by JarzaClay** [Qosmetics/Qosmetics-Notes#12]
|Info| Beat Saber: v1.27.0_3631150051 - Qosmetics: v0.1.3 - Discord: Jarza#6969 - Contact me for more questions

I accidentally came across this bug while playing Beat Saber. I enabled smaller notes for something to do, but the size didn't seem to change. I also noticed that some of the notes I was hitting shouldn't have counted as cuts. I quickly realized that the hitbox was not the correct size, and decided to investigate more. In [this video](https://youtu.be/OtQkDYzuIfs?t=29) by Bandoot, he explains that the hitbox is left unchanged, but the note appears smaller. It seems as if the Beat Saber devs got lazy, and just decided to scale the hitbox up by 50% (as the note is 50% smaller) instead of just setting the hitbox to a set number, because there shouldn't be a problem in the base game. Unfortunately, modding changes this, and since the note can go up to 2x bigger (and potentially larger with mods that change slide bar limits), the hitbox scales with it. The note also stays the size that is set by Qosmetics, so another good change would be to implement 50% scaling down AFTER the Note size change from Qosmetics. I've included some footage of the bug, and also a ranking submission that uses this bug (I will be overriding the rank submission after this)

[Non-Ranked play](https://youtu.be/Fr3kCtFD6qQ) --- [Ranked play](https://youtu.be/oAtgmXaJb40)

**Comment by RedBrumbler** [comment]
Fixed according to @JarzaClay , with the release of v0.1.5
